name: stripecard
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  # manually added dependency
  get: ^4.6.1
  flutter_screenutil: ^5.9.0
  google_fonts: 5.1.0
  country_code_picker: 3.0.0
  material_design_icons_flutter: 7.0.7296
  get_storage: ^2.0.3
  logger: 2.0.2
  pin_code_fields: 8.0.1
  intl: ^0.18.0
  image_picker: 1.0.4
  dotted_line: ^3.1.0
  flutter_svg:
  percent_indicator: ^4.2.3
  qr_code_scanner: ^1.0.1
  flip_card: ^0.7.0
  dotted_border: ^2.0.0+3
  carousel_slider: ^4.2.1
  dart_code_metrics: ^5.6.0
  connectivity_plus: 4.0.2
  flutter_spinkit: ^5.1.0
  flutter_html: ^3.0.0-alpha.6
  flutter_inappwebview: ^5.7.2+3
  patterns_canvas: ^0.4.0
  cached_network_image: ^3.2.3
  iconsax: ^0.0.8
  

dependency_overrides:
  http: ^1.1.0

  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner:
  flutter_app_name: ^0.1.0

  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "StripCard"


flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  
  fonts:
    - family: AgencyFB
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf

  assets:
    - assets/card/
    - assets/clipart/
    - assets/icon/
    - assets/logo/
    - assets/onboard/
    - assets/qr/
    